### ISSUE TITLE
Change default entry for Add Attendance from Anti-Paladin to a non-selectable

### ISSUE THREAD

**Issue by Glenalth** [amtgard/ORK3#102]
https://www.facebook.com/groups/189406377888489/permalink/673955716100217/

Idea is just to add an extra field of "-select one-" or similar that would not be considered a valid entry so that Anti-Paladin isn't being accidentally assigned due to being the default.

**Comment by jrtaylor-com** [comment]
@esdraelon Branch https://github.com/amtgard/ORK3/tree/enhance/player/issue102-add-default-select-option should resolve this issue.

**Comment by esdraelon** [comment]
Fixed and released sprint-2017-10-16
