### ISSUE TITLE
Reeve Qualified flag and report

### ISSUE THREAD

**Issue by Glenalth** [amtgard/ORK3#115]
A reeve qualified report was requested.
May need a Guildmaster of Reeves login added to chapters for maintenance of reeve qualified status.

A couple of challenges in this as groups don't necessarily do it the same way.
May need a kingdom option to select if it's a 6 month (or longer) term from test date or if it's a term that lasts until the end of the current reign.

**Comment by Glenalth** [comment]
It's been brought up that a similar Corpora Qualified flag would be useful for some places as well.

**Comment by Hunteil** [comment]
Thinking this would be useful for Kingdom level GMR to control. The tricky part is getting them to follow up on it. I think your term idea would help enforce reeve qualifications. And maybe a default of 12 months would be adequate. But allowing the admin to adjust in 3 month increments would suffice too. Then when it comes to profiles losing their reeve quals, it'll happen staggered depending whoever they are qualing for. i.e. Our Kingdom monarchy is 3 months apart from our lower level monarchies (KCG).

Also allowing lower level PMs to update these would help too.

This way after quals, I'd Personal message my Kingdom GMR and local PM to ensure it gets entered.

**Comment by jrtaylor-com** [comment]
The above PR implements the requested reeve and corpora tracking as well as kingdom and park level reports for both.
