### ISSUE TITLE
Add date awarded to Player_awards report

### ISSUE THREAD

**Issue by Glenalth** [amtgard/ORK3#117]
There was a request to add the date awarded to the player_awards report.

This would let the report show all of the awards given at specific events or just recent history.

**Comment by jrtaylor-com** [comment]
@esdraelon Branch https://github.com/amtgard/ORK3/tree/enhance/report/issue117-player-awards-date-col should resolve this issue

**Comment by esdraelon** [comment]
Fixed and released in branch sprint-2017-10-16
