### ISSUE TITLE
Display of apostrophes in dropdown menus

### ISSUE THREAD

**Issue by Glenalth** [amtgard/ORK3#119]
Apostrophes are showing up with escape character in drop down menus. Unsure if other characters are being affected.

Observed in player search at top of each page, player field in award entry forms, and player fields on unit admin page.

**Comment by esdraelon** [comment]
It also prevents searching.

**Comment by jrtaylor-com** [comment]
@esdraelon @Glenalth can you provide an example to recreate? I search for Wynd and "Dame Mistress Wynd o'Onyx Loch von Drakken" appears in the dropdown without any escape character.

**Comment by Glenalth** [comment]
It looks like @esdraelon fixed it.
