### ISSUE TITLE
remote authentication

### ISSUE THREAD

**Issue by mathus13** [amtgard/ORK3#120]
Is there any capability of / documentation for authentication against ork3? 
I am writing some functionality for goldenvale and would like to authenticate users against the ork and be able to pull back the user profile (email, player name, persona name).

**Comment by esdraelon** [comment]
Authentication is exposed via the JSON endpoints; the token can be used in
subsequent calls for fetching user data, I believe.

**Comment by esdraelon** [comment]
https://github.com/amtgard/Ork3JsonRpc in C#

https://github.com/amtgard/orkmobile/blob/master/js/ork.js in the Ork.login() function
