### ISSUE TITLE
Add dues expiration date to dues paid reports

### ISSUE THREAD

**Issue by Glenalth** [amtgard/ORK3#127]
Something useful for the chancellors. Can probably replace the "Suspended Until" column on that report.

**Comment by jrtaylor-com** [comment]
Branch https://github.com/amtgard/ORK3/tree/enhance/reports/issue127-add-dues-through should resolve this @esdraelon

**Comment by esdraelon** [comment]
Fixed and released in branch sprint-2017-10-16
