### ISSUE TITLE
Paragon Report

### ISSUE THREAD

**Issue by Glenalth** [amtgard/ORK3#128]
A report showing all of the class masters/paragons for a specific chapter or kingdom.

For kingdoms to organize their paragons since at least one now has a Circle of Paragons and to help other players locate paragons for apprenticeship.

**Comment by Hunteil** [comment]
Our Kingdom (KCG) uses a google doc to track this currently b/c there's no way on ORK.
Here is a reference for how ours looks: https://docs.google.com/spreadsheets/d/1Uyfp7LR5nmexCn4DsRkq3Ya2a5q9Ef8lyvJ6J1aJgYQ/edit#gid=0

PS: wasn't saying it needed to reflect all those data points. Just an example.

**Comment by jrtaylor-com** [comment]
@esdraelon Branch https://github.com/amtgard/ORK3/tree/feature/report/issue128-added-class-masters-report should resolve this issue.

**Comment by esdraelon** [comment]
Fixed and released

**Comment by esdraelon** [comment]
Released sprint-2017-10-16
