### ISSUE TITLE
Paragon Report - Missing Wizard and plz add column & update noun

### ISSUE THREAD

**Issue by Hunteil** [amtgard/ORK3#143]
1. Paragon/Class Master list seems to be missing Wizard.
2. Recommend changing report name of "Class Masters"  to "Class Paragons" to stay up with RoP noun.
3. Also can you add a column for last attendance date please? This way, any potential candidates /and/or Monarchy can see who are the most active to communicate with.

**Comment by jrtaylor-com** [comment]
1. https://github.com/amtgard/ORK3/tree/fix/db/update-master-wizard-peerage
2 & 3. https://github.com/amtgard/ORK3/tree/fix/reports/issue143-class-master-add-attendance-n-paragon-noun

@esdraelon these branches are ready for review
