### ISSUE TITLE
Awards table missing denormalized reference to award table

### ISSUE THREAD

**Issue by esdraelon** [amtgard/ORK3#148]
When awards are added to the ork_awards table, the denormalized reference to award.award_id is not preserved. The kingdomaward_id is referenced, which allows for reconstruction of the original award references.

**Comment by jrtaylor-com** [comment]
@esdraelon Resolve for this issue is ready in this branch: https://github.com/amtgard/ORK3/tree/fix/awards/issue148-missing-award-id-on-save
