### ISSUE TITLE
Dues Paid Report showing wrong date for some players

### ISSUE THREAD

**Issue by Glenalth** [amtgard/ORK3#165]
The dues paid report is showing the wrong dues expiration date for some players. Unsure on how widespread this is, but I have examples from two chapters.

Examples...

I am listed as being Dues Paid on player record until 2015-09-01
https://amtgard.com/ork/orkui/index.php?Route=Player/index/3795

On report it shows 2018-03-09
https://amtgard.com/ork/orkui/index.php?Route=Reports/duespaid/Park&id=68

I think this is about the same amount of difference as when a previous PM erroneously revoked my dues, so it might be related to that. Other players in my chapter seem fine.

I had another person come to me showing inactive players being dues paid on the report, but not on the player pages. They seemed to think it was correct on the player page, but not on the report.

Their example player.
https://amtgard.com/ork/orkui/index.php?Route=Player/index/87283
https://amtgard.com/ork/orkui/index.php?Route=Reports/duespaid/Park&id=665

**Comment by jrtaylor-com** [comment]
Looks like the issue presented when the player was associated with multiple kingdom treasury accounts. Doing a lookup for kd id on parks and passing it with the query resolves the issue.

@esdraelon branch https://github.com/amtgard/ORK3/tree/fix/reports/issue165-incorrect-dues-paid-dates should resolve this issue and is ready for review
