### ISSUE TITLE
Player dues paid doesn't transfer between kd park move

### ISSUE THREAD

**Issue by jrtaylor-com** [amtgard/ORK3#167]
Player previously played at park A and was dues paid.
Xfered to another local park (B), played a couple years was dues paid.
Xfered back to Park A and old dues paid date is showing for park A.

Both records exist for player under table ork_split.

@Glenalth can you add expectations of what should occur on player move with dues for both same kd and new kd? We may just need to select the first future date dues expiration for the players current kd for display without any logic change.

**Comment by Glenalth** [comment]
The behavior needed varies between kingdoms. Leaving dues attached to chapters with the kingdom dues paid report checking against every chapter in the kingdom should support the vast majority of kingdoms.

For transferring to a new kingdom, dues should not transfer at all.

Transferring within a kingdom has several needed outcomes...
Chapter dues: removed, kingdom dues: kept
Chapter dues: removed, kingdom dues: removed
Chapter dues: kept, kingdom dues: kept
