### ISSUE TITLE
URL field for units is not available on unit admin page

### ISSUE THREAD

**Issue by Glenalth** [amtgard/ORK3#175]
URL field for unit website is not available on unit admin page and cannot be updated. 

It is available on the unit creation page and is displayed on the unit page.

**Comment by jrtaylor-com** [comment]
Admin Template: `/orkui/template/default/Admin_unit.tpl`

**Comment by jrtaylor-com** [comment]
Controller: `/orkui/controller/controller.Admin.php` 
I believe the `unit` method beginning on line 99 is what processes the update (at a quick glance) and it looks like it had the `Url` update there, so it appears to just be a display issue o the Admin Template
