### ISSUE TITLE
Park Names with apostrophes don't auto populate in attendance screen

### ISSUE THREAD

**Issue by buddy1616** [amtgard/ORK3#181]
When entering attendance, park names with apostrophes don't completely auto-fill in the park field. It stops at the apostrophe. For example, "Raven's Roost" comes through as just "Raven" and the rest must be typed out. A somewhat minor inconvenience, but it does get pretty old having to enter the park name for each player for attendance.

This may be a related to https://github.com/amtgard/ORK3/issues/37, and makes me think similar logic was used in both places (though I haven't looked at any code). This issue probably pops up any place this logic is used.

**Comment by esdraelon** [comment]
Special characters escaped for great goodness. Closed with #37
