### ISSUE TITLE
Chapter unit report showing incorrect owners

### ISSUE THREAD

**Issue by Glenalth** [amtgard/ORK3#185]
Unit report showing a member that is not a manager or creator as an "owner". Unsure if it's just a misnamed header in the table or something else is supposed to be going on there.

"Companies and Households" report link example: https://amtgard.com/ork/orkui/index.php?Route=Unit/unitlist&ParkId=55

User that discovered the issue.
https://www.facebook.com/groups/orkupdates/permalink/1006754559486996/

**Comment by esdraelon** [comment]
There is no concept of an owner. Units do not enforce managers or creators, so the report cannot be keyed off of those concepts.

Additionally, the intent of the report is to show that the unit has representation in the related object (kingdom or chapter).

**Comment by esdraelon** [comment]
Removed "owner" field.
