### ISSUE TITLE
Correct Dues Issues

### ISSUE THREAD

**Issue by esdraelon** [amtgard/ORK3#188]
https://github.com/amtgard/ORK3/issues/94
https://github.com/amtgard/ORK3/issues/113
https://github.com/amtgard/ORK3/issues/165
https://github.com/amtgard/ORK3/issues/167
https://github.com/amtgard/ORK3/issues/174

Remove treasury, create a dues paid table:
dues_id
mundane_id - player
kingdom_id - dues paid to
park_id - dues paid to
created_on - record created at
created_by - record created by
dues_from - start date for dues
terms - number of terms
dues_until - last date dues are valid (may be null)
dues_closed_from - if closed early, original termination date
dues_for_life - boolean (dues for life)

By default, close dues when a player transfers between kingdoms.
By default, close dues for all players at a park that transfers between kingdoms.
Allow an option for holding dues during transfers.

Update report class with new dues table.

**Comment by jrtaylor-com** [comment]
> By default, close dues when a player transfers between kingdoms.
> By default, close dues for all players at a park that transfers between kingdoms.
> Allow an option for holding dues during transfers.

Dues should always hold over really, aren't most kingdoms Non Profits? Technically transferring your credits to a different kingdom doesn't revoke your relationship with that organization. Bigger picture is that someone can and should be able to be a member of multiple kingdoms (orgs) unless there is a disassociation, or a membership requirement that requires physical residency, or unique membership

Thoughts?

**Comment by jrtaylor-com** [comment]
I think a column for "revoked" boolean would be useful as well

**Comment by Glenalth** [comment]
Locally, Transferring to another Kingdom ends your membership and voting rights with the kingdom.

**Comment by kenwalker** [comment]
I think there are people with random “dues paid forever” get really upset if it is not propagated. This is a higher level question that should be asked.

**Comment by jrtaylor-com** [comment]
When I say "hold over" I meant, they should not be "canceled" or "revoked" with the entity they paid toward. I think displaying dues in a situation like this would show what kingdom/park that dues entry is tied into.

Analogy:
You pay rent for an apartment on Main Street. But you are moving to to the East side and have gotten an apartment there. You are paid up through the month on Main Street. Just because you dont sleep there doesn't give that apartment owner the right to change the locks until your lease runs out.

**Comment by tzulah** [comment]
> I think there are people with random “dues paid forever” get really upset if it is not propagated. This is a higher level question that should be asked.

In my kingdom, dues paid for life is specifically tied to our kingdom ONLY.  It is understood that dues paid do NOT transfer to any other kingdom.  I think jrtaylor's comment is exactly relevant.  Furthermore, if that player moves back to the original park, they should still be dues paid for life, I would think?

**Comment by jrtaylor-com** [comment]
![Screen Shot 2021-04-15 at 1 38 24 PM](https://user-images.githubusercontent.com/2745760/114921186-e33b7000-9def-11eb-82f0-a05a0df3add3.png)

With this layout I am using, the records are maintained regardless of where they switch to and it's presented that way. Revoked records can be seen in the admin view. If a park changes kingdoms, the view will reflect their dues in both kingdoms and that can be seen visually
