### ISSUE TITLE
Reports including Crown Qualified lists fail for principalities

### ISSUE THREAD

**Issue by Glenalth** [amtgard/ORK3#198]
The Knights & Masters report and the Masters report fail to display anything for Principalities. Other reports seem fine. Unsure if this was the case before the Crown Qualified reign totals were added or if it is just something that was missed with the initial implementation.

**Comment by jrtaylor-com** [comment]
@Glenalth is this still valid after the switch to Order of the Crown was implemented?

**Comment by Glenalth** [comment]
Only if they were trying to run reports to use for granting initial crown orders. It can probably be axed at this point.
