### ISSUE TITLE
JSON-based Federation

### ISSUE THREAD

**Issue by amtgard** [amtgard/ORK3#2]
The existing federation system uses SOAP.

I have a working federation model (from another project), that leverages JSON-based RPCs, and definitely works.  Some care will have to be taken around authentication and session storage, but it will probably be easier than making sure that every last SOAP call is properly constructed in the WSDL, especially if we plan on having a moving target for the API for a while.

**Comment by BenOvermyer** [comment]
Is this still relevant? @esdraelon

**Comment by esdraelon** [comment]
No
