### ISSUE TITLE
[Waiver] Upload needs succes/failure notification

### ISSUE THREAD

**Issue by jrtaylor-com** [amtgard/ORK3#20]
Old Ref: B59

Verify waiver upload/report failure information

Old Ref: B87

waiver is in a PDF. upload it, and it removes waivered status from player.

[Tuncer]: They likely lose waivered status due to an error however since a notification isn't displayed the user assumes it was uploaded when the system nulled the field thus losing the waivered status.

**Comment by Glenalth** [comment]
Waivers no longer saved on ORK.
