### ISSUE TITLE
Player Search Enhancements

### ISSUE THREAD

**Issue by Glenalth** [amtgard/ORK3#205]
Modify player search to allow for the use of chapter/kingdom abbreviations to limit the search results in cases of common names. If this can be done inside the normal search box, that would be ideal.

**Comment by esdraelon** [comment]
enhancement/205-player-search-enhancements

Syntax:

K[2,3]:P[2,3]|* player name

So:

CK:* megiddo
CK:NOC megiddo
KOP:* michael
