### ISSUE TITLE
Would like a limit on Player/AttendanceForPlayer

### ISSUE THREAD

**Issue by kenwalker** [amtgard/ORK3#209]
I'm writing an application in which I'd like to show the last attendance a user had.  As it is, there's no limit on the AttendanceForPlayer API call so you get all the records.  I'll submit a pull request with the limit parameter optional for this API call so that my app won't waste unnecessary bandwidth on devices to retrieve this player detail.

**Comment by mathus13** [comment]
Do you see this best as a date limit or a count by December order

**Comment by kenwalker** [comment]
For now by descending order since that's an easy change. Date would also be very useful for computing if someone was attendance qualified for example (N times in last M months where the computation is not the same as what's used by the ORK proper) and so you don't need to retrieve ALL their attendance.
I may do that as a follow on PR.

**Comment by kenwalker** [comment]
I mean count from current attendance down to zero from the limit parameter.  My wording above was not great.

**Comment by mathus13** [comment]
fixed in  #210
