### ISSUE TITLE
Minor Header UI Adjustments

### ISSUE THREAD

**Issue by intergalexic** [amtgard/ORK3#214]
![](https://screenshot.click/24-28-qy2pd-fp0wo.png)

User experience as a first-time admin is a little strange. A couple thoughts:

1. Move **Home** all the way to the left, keeping it static.
2. Change **Admin** to **Admin Panel**, similar to old forums and making it very clear that's where our options are.
3. Prefix **Logged in as** to username for clarity.
4. Hide Player/Park function with **Search** link, changing to the fields on click.

**Comment by esdraelon** [comment]
feature/214-rearrange-header-bar
