### ISSUE TITLE
Inactive Report broken for one chapter

### ISSUE THREAD

**Issue by Glenalth** [amtgard/ORK3#220]
Seven Sleeping Dragons Inactive player report is blank. Chancellor recently marked a bunch of players as retired and they were showing up on the report as of a few weeks ago.

Checked a few other chapters and did some tests on a defunct chapter and it seems to be working fine for them. Also marked one of Seven Sleeping Dragons players as active and they appear in the roster, but when marked as retired they do not show on the inactive list.

Report in question: https://amtgard.com/ork/orkui/index.php?Route=Reports/inactive/Park&id=128

One user that should be on that report: https://amtgard.com/ork/orkui/index.php?Route=Admin/player/109642/update

**Comment by Glenalth** [comment]
Discussion about bug: https://www.facebook.com/groups/orkupdates/permalink/1253616454800804/

**Comment by esdraelon** [comment]
This is a caching issue.
