### ISSUE TITLE
Report/PlayerAwards not returning multiple awards on same date

### ISSUE THREAD

**Issue by kenwalker** [amtgard/ORK3#224]
If you look at the following player profile and their awards, they were awarded 2 Garbers on the same date 2003-01-01.  They should have a total of 8 Garbers.

https://amtgard.com/ork/orkui/index.php?Route=Player/index/2657

If you run the park report for awards, this same person then shows up with only 7 Garbers. 

I think the query has a **distinct** set that includes the date?  But I have no idea really ;-)  I'm trying to write some kingdom reports for Iron Mountains and this is interfering with accuracy of the report.  Is there a way to not set distinct on the date but the rest?

https://github.com/amtgard/ORK3/blob/master/system/lib/ork3/class.Report.php#L275

**Comment by kenwalker** [comment]
If I add **awards_id** following to the query, then all the items for that player are returned. There are quite a few changes overall for the kingdom though. Would need to ensure they were legitimate changes

award_name, m.persona, ma.date, **ma.awards_id,** m.mundane_id, ma.rank

**Comment by Glenalth** [comment]
Technically they have 8 0th level garbers, that alone will confuse most of the reports. They need to be reentered with actual levels at some point.

**Comment by kenwalker** [comment]
I have code that counts them and takes max of that or Rank.  Seems to work fairly well. It's what I'm using in mORK (which only queries current player) and a new tool for ladder candidates. It's not optimal, yes, they should be entered properly.  But for now, the reports should at least return them all.

**Comment by kenwalker** [comment]
Pretty sure this was fixed by https://github.com/amtgard/ORK3/commit/6c0bde5806bf615624a755e9e034a6b27eab187e

Closing
