### ISSUE TITLE
Kingdom custom awards not appearing in drop down lists

### ISSUE THREAD

**Issue by Glenalth** [amtgard/ORK3#253]
> "My kingdom (Desert Winds) has a few custom awards set up (in this specific case, Order of the Roach) that don't appear when entering awards, either through the Enter Awards link or the Add Award menu on a player's profile admin panel."

Some info here.
https://www.facebook.com/groups/orkupdates/permalink/1592252024270577/

**Comment by jrtaylor-com** [comment]
It's a query issue, the WHERE clauses reference a column that isn't shared between award and kingdom award tables. Meant to comment earlier about this but I'm working. 

This evening I'll do some testing and get a PR out

**Comment by jrtaylor-com** [comment]
PR above is ready for testing
