### ISSUE TITLE
Reverse order of heraldry & image

### ISSUE THREAD

**Issue by jkat718** [amtgard/ORK3#255]
With the current order, the heraldry comes first and is therefore what is used in web previews (like on Facebook). Since, anecdotally, more people have images set than heraldry, this mean most ORK page profiles just have the placeholder image in their previews. By reversing the order, the more commonly-used field is on top and more accessible *and* would be used for previews.

**Comment by jrtaylor-com** [comment]
This request doesn't actually require the template be "reordered". We just need to add an og meta tag in the header. EX: `<meta property="og:image" content="http://euro-travel-example.com/thumbnail.jpg">`
I dont think we are passing player info in the header at the moment, but I'll take a look

**Comment by jrtaylor-com** [comment]
In the interim I've created the above PR that sets the ogimage meta tag to use the ORK's logo. This is a quick compromise for a better social media linking experience. At some point we can see about passing more data to the header that could be use logic to display either the headshot or the heraldry if they exist. At that point we could also update the title to be more descriptive which would help what your request is going for.
