### ISSUE TITLE
[Feature Request] Pronoun Field

### ISSUE THREAD

**Issue by jkat718** [amtgard/ORK3#256]
A player approached me and asked if I could request that a field be added to the ORK for a player to put their pronouns (he/him/his, she/her/hers, they/them/theirs, xe/xir/xirs, and so on). I told them I'd follow up with the ORK team, so I'm submitting a feature request ticket on their behalf. Is this within the scope of the ORK? I think it's probably a better place for it than the Amtwiki, which is the current solution I give people who ask me about this.

**Comment by Glenalth** [comment]
It should be made available somewhere. At the moment the only real personal information we store on the ORK account is player name and even that is hidden from most users. Adding more visible personal information is something that would need to be looked into.

**Comment by jrtaylor-com** [comment]
@jkat718 can you provide a full list of the "So On" ? It's easier to approach from a technical aspect if all of the requirements are listed.
Thanks!

**Comment by jrtaylor-com** [comment]
I spoke with Dallen about this yesterday and have an idea of what can be used referencing a link that was provided: https://uwm.edu/lgbtrc/support/gender-pronouns/?fbclid=IwAR3Z0-GLEMFVlWEmU1YFecvN2MiYuKlab45tIDebo9NxkgOS9c1ZOMVs67k

**Comment by Glenalth** [comment]
It might be a better option to put on the Wiki instead of adding more personal information to the ORK.

**Comment by LealFitzmorgan** [comment]
Just wanted to upvote this ticket! Game pronouns aren't always the same as mundane pronouns for folks so it might not even be something that might be considered personal information in that sense.

**Comment by ValoryFox** [comment]
Agreed! My suggestion for the specific input field would be a <input> + <datalist> combo box. Have he/him she/her and they/them as default suggestions, maybe with the addition of "Ask me" & "Any pronouns"? That way people can type any neopronouns or other descriptions.

**Comment by jrtaylor-com** [comment]
Feature is live with 2022NOV-19-RELEASE
