### ISSUE TITLE
Hide expiration date when DFL is selected

### ISSUE THREAD

**Issue by jrtaylor-com** [amtgard/ORK3#269]

**Comment by jrtaylor-com** [comment]
Similar to the kingdom level Dues Report: 
![Screen Shot 2021-04-20 at 1 49 58 PM](https://user-images.githubusercontent.com/2745760/115448499-62a9b480-a1df-11eb-93cd-00e62427da67.png)

When viewing the Player's page, if the entry is Dues For Life flagged, it should not show an expiration

![Screen Shot 2021-04-20 at 1 51 57 PM](https://user-images.githubusercontent.com/2745760/115448725-a8667d00-a1df-11eb-8d78-292a64304238.png)

The Expiration field should be blank (but green) and the Dues for Life cell should be highlighted green like the expiration cell for better visibility.

**Comment by jrtaylor-com** [comment]
File: Player_index.tpl

**Comment by kenwalker** [comment]
The Player page change is good. The others still show the dates, so don't close this issue yet
