### ISSUE TITLE
Update DuesPaidList sort back to pre mOORK mods

### ISSUE THREAD

**Issue by jrtaylor-com** [amtgard/ORK3#270]
`$sql .= "  group by d.mundane_id order by d.dues_until DESC, m.kingdom_id ASC, m.park_id ASC, m.persona ASC";`

Move priority of `d.dues_until DESC` back to the end of the statement since we are fixing the mORK compatibility sort in the controller.

This will fix the report sort display

**Comment by himanshu007-creator** [comment]
i would like to work on this issue.

**Comment by jrtaylor-com** [comment]
You should be able to locate it in the class file by searching for `order by d.dues_until` class.Report.php `GetDuesPaidList` method
