### ISSUE TITLE
[Events] Fatal Error

### ISSUE THREAD

**Issue by jrtaylor-com** [amtgard/ORK3#3]
Old Ref: B4

 I was trying to make Ice Haven Quals an event, but got this error when I put Ice Haven in the park field: "Fatal error: Call to a member function GetParkShortInfo() on a non-object in /home/amtgard/amtgard.com/ork/system/lib/ork3/class.Event.php on line 309"

**Comment by amtgard** [comment]
Superceded by other code changes.
