### ISSUE TITLE
Trim Whitespace from Searchable Fields

### ISSUE THREAD

**Issue by jkat718** [amtgard/ORK3#314]
Searching "Persona" will not return a user whose persona name was accidentally set to "Persona " (note the trailing space). Ideally, leading and trailing whitespace would be stripped from existing usernames, persona names, and mundane names, but that could theoretically cause ripple issues. At the very least, validating those fields for new users will mitigate the issue on future records.

**Comment by jrtaylor-com** [comment]
Fix is live with 2022NOV-19-RELEASE
