### ISSUE TITLE
Make Default Status Active/Visible instead of Inactive/Retired

### ISSUE THREAD

**Issue by jkat718** [amtgard/ORK3#318]
It is my understanding this default was made to allow the initial import of mostly-inactive records from the ORK2 easier, but since then it has caused nothing but headaches. I think it's a safe assumption that, if someone is creating a player profile, that player is active. If the issue is that profiles may be set up with only one or two attendances and then left to rot in "Visible but Inactive" hell, maybe just a check when attendance is entered to reactivate someone who's inactive, and a chron job to mark any active profiles that haven't attended in X days as inactive? After the initial large wave of marking-as-inactive, the set of Visible players should shrink considerably.

**Comment by jrtaylor-com** [comment]
https://github.com/amtgard/ORK3/blob/9fdd43d8bc5e1308ebf39a7e5ac86b0782b0b535/orkui/controller/controller.Admin.php#L1108 

I updated this 5 years ago in 2017 https://github.com/amtgard/ORK3/commit/6d39b49f5752b6c8551d0e1622bcce9a59d32f94 

Are you seeing some other behavior when creating players?

**Comment by jkat718** [comment]
Nope, looks like the user was claiming profiles from another park, and the profiles they were claiming were just older than that fix. I've set the profiles in question to be active, they should be good now.
