### ISSUE TITLE
I was able to give myself admin access. 

### ISSUE THREAD

**Issue by TaintedHolyWater** [amtgard/ORK3#331]
The title really says it all. Can someone in charge please contact me? This is a security issue so I’d rather not describe the process publicly. 
As of now I can edit, delete or add anything to anyone’s account instead of just at the local park level where I should have access.

**Comment by jrtaylor-com** [comment]
In charge is such a loose term heh. On FB, reach out to Jason Katzner, GrandDuke Fog, Ken Walker, or Noah Smith on the FB group https://www.facebook.com/groups/189406377888489 for a private convo about the issue you have discovered.

**Comment by TaintedHolyWater** [comment]
Thank you very much. Admittedly I don’t know a lot about ork, just wanted to report it to the right people after stumbling across the problem.
