### ISSUE TITLE
Cannot Reconcile Credits

### ISSUE THREAD

**Issue by symplocos-tinctoria** [amtgard/ORK3#339]
I am unable to transfer credits for several of my park members. I'm guessing this is a system-wide issue. Kingdom: Northern Lights. Land: The Hollow

**Comment by ash402** [comment]
Are you sure there is a code problem? I tested the Reconcile interface this on my own ORK profile, and it seemed to work correctly.

**Comment by kenwalker** [comment]
@symplocos-tinctoria can you list the steps you took that failed? I can try to replicate locally then and see what's wrong

**Comment by symplocos-tinctoria** [comment]
I no longer participate in Amtgard due to the abuse and bullying which the
organization is not interested in addressing. This game is unsafe and I
recommend that everyone, especially women and minors, avoid it altogether.
The ORK issue is of no concern.

**Comment by kenwalker** [comment]
Understood. If you would like to discuss the above further, please don't hesitate to reach out to our Ombudsmen program. I'll close this bug report in the meantime
