### ISSUE TITLE
Admin > Ban Player Gives 500 Error

### ISSUE THREAD

**Issue by jkat718** [amtgard/ORK3#340]
From the index page, Admin Panel > ORK Management > Players > Ban Player directs to [https://ork.amtgard.com/orkui/index.php?Route=Admin/banplayer](https://ork.amtgard.com/orkui/index.php?Route=Admin/banplayer), which generates HTTP error 500.

**Comment by kenwalker** [comment]
I'm not sure why this page is used vs. the Kingdom pages for bans but this fix should allow it to work again. I added the URL to the banned player's page so there's more information too look at. The info that comes back for that list has not much to display.

**Comment by kenwalker** [comment]
Released and confirmed fixed on site
