### ISSUE TITLE
[Treasury] UI

### ISSUE THREAD

**Issue by jrtaylor-com** [amtgard/ORK3#4]
Old Ref: B5

Treasury has no public interface, and needs one.

**Comment by jrtaylor-com** [comment]
@Glenalth I've never used the Treasury features before, if you have any insight here on how treasury is handled through the ORK currently I can see about adding an interface. When I click through Treasury links they end up on the KD list page and nowhere useful.

**Comment by Glenalth** [comment]
It's not handled at all except that Dues entries go onto a ledger of some sort, but that's all @esdraelon  stuff. Some sort of full double entry accounting system that is unfinished.
