### ISSUE TITLE
[Attendance] Bad links

### ISSUE THREAD

**Issue by jrtaylor-com** [amtgard/ORK3#43]
Old Ref: B88

"the park listings when entering attendance for an event dont actually link to the park, they just go to a blank thing. to replicate ""-Enter ork page
-Log onto account
-select the NW page
-Select ""admin""
-select ""events""
-select ""summer coronation""
-select event dated 8/16 on the ""attendance"" tab
-enter person for attendance
-right click on the park cell that populates for that listing, and select ""open link in new tab"""""

**Comment by jrtaylor-com** [comment]
@esdraelon branch https://github.com/amtgard/ORK3/tree/fix/events/issue43-bad-park-links will resolve this issue

**Comment by esdraelon** [comment]
Fixed and released in branch sprint-2017-10-16
