### ISSUE TITLE
[UI] Admin profile Edit shows only Companies and not Households.

### ISSUE THREAD

**Issue by Hunteil** [amtgard/ORK3#61]
I went into my profile normally and I can see my Companies & Households in the table like normal. I went into admin mode on my profile and the Companies & Households Table only displayed my single Company. (I have admin rights for all my households and companies so it's strange it only shows the single company.) I went to the Company page and admin'd it and changed it to Household. Now the profile admin view no longer shows the single listing. It shows nothing now. In the normal profile view, it still lists everything just fine and it updated correctly.

So from what it sounds like. The Profile Admin view of the "Companies & Households" table is only displaying Companies.

**Comment by Glenalth** [comment]
Verifying this, a few players have run into the issue when trying to quite households.

**Comment by jrtaylor-com** [comment]
Confirmed this issue, reproduce by locating a player with both Household and Company affiliations. Click the admin link and you will only see companies listed.

**Comment by jrtaylor-com** [comment]
PR #122 will resolve this issue. Problem was a type in the household variable.
