### ISSUE TITLE
[company] can not readd people who have left or been removed

### ISSUE THREAD

**Issue by Tyedye** [amtgard/ORK3#65]
sometimes accidents happen, and people dont like living with them, so removing the restriction against readding people who are removed from a company or household would cut down on complaints a bit.

**Comment by jrtaylor-com** [comment]
I think the easier route for this would be to update the UI to present a confirmation modal for links that have a delete action tied to them. All of the company/unit X and Quit links currently delete without confirmation. What do you think @Glenalth

**Comment by Glenalth** [comment]
The restriction against re-adding people winds up being an issue big enough that units have had to delete their unit and recreate it to put members back in that either left accidentally or sometimes on purpose. It feels like a feature that causes more issues than it solves.

In a perfect world, the user being re-added to the unit would need to confirm the action before it actually happens or the user would need to apply to the unit and then be approved by a manager.

**Comment by Glenalth** [comment]
This is also related to #38

**Comment by jrtaylor-com** [comment]
PR #123 will resolve this.
