### ISSUE TITLE
[Installation] Create installer

### ISSUE THREAD

**Issue by zellfaze-zz** [amtgard/ORK3#69]
Currently the software lacks any installation script.  This makes it more difficult to set up again if needed and also limits the ability of others to build on and re-use this code base.

We should create some sort of installation script that is launched automatically if this is a new installation and collects database information and then sets up all of the database tables and adds an initial admin user.

**Comment by jrtaylor-com** [comment]
We incorporated Docker and updated the README with the appropriate steps.
