### ISSUE TITLE
Hide administrative functionality

### ISSUE THREAD

**Issue by zellfaze-zz** [amtgard/ORK3#71]
You should hide any modification functionality that the current user does not have access to.  This covers you on two fronts.  It protects you a little bit in case you accidentally do not sanitize your input quite right (though I wouldn't rely on it) and it helps prevent users from getting confused.  There is something distinctly confusing about having an interface full of editing options and yet not being allowed to use any of them.  It is entirely possible for someone to spend an awful lot of time tweaking some settings only to find in the end they can't save them.

**Comment by jrtaylor-com** [comment]
If a user is going into the admin section, they are going to see controls. Agreed that adding some indicators on logged in user permissions, which as Ben linked is a part of issue #60. Closing this one out.
