### ISSUE TITLE
local authorization attempt log in bug

### ISSUE THREAD

**Issue by Tyedye** [amtgard/ORK3#72]
Bearskull contacted me today, asking why he has to request a password every week. He reports that the password goes away after a week, even when he manually sets it, giving an error of "Login and username could not be found. Local Authorization Attempt" when he tries to log in. Others have reported this issue, but it has been fixed when they request and set a new password. I attempted to set his password to something, and neither he nor I was able to log in with two different passwords. 

Not really sure what else to try. I think it is different than the session issues, since we are setting a new password and it still isnt working.

**Comment by Tyedye** [comment]
This may be a continuation of this bug, or may not be. 

Phillip Brown, username Bro Marcus from the Northern Lights has a password that will not stay changed. I set his password when logged in as myself, and then attempted to log in to his account with that password, it did not work. He requested a password, and I was able to log in using it, but after changing his password while logged in as him, I was still unable to use that new password to log in.

There is no error text beyond "Login and username could not be found. Local Authorization Attempt"

He is the incoming PM for his park, and, understandably, does not wish to have to get a new password at least once a week.

**Comment by Tyedye** [comment]
Slight updated. Glenalth pointed out that most usernames dont have spaces, so I changed his username to bromarcus. I tried updating his password while logged in to my account. it did not work.

I then opened an incognito window in chrome, logged in as myself, and changed his password. I was then able to log in as him, both in the incognito window and in a normal window. I tried to change his password while logged in as him in the normal window, and it made neither password work.  

I can at least set a password for him now, using the incognito window, but hopefully this extra information will help with tracking down whatever is causing it.

**Comment by amtgard** [comment]
I think there are lingering issues around session caching:

1. The configuration for cache clearing on the box is not aggressive enough
(I encountered this with other domains hosted at the same provider), and
2. I don't know enough about session caching to effectively work with it

I think the solution may be to move the ORK to the new iron provided to us.

Noah
