### ISSUE TITLE
Editing Unit "members" fills in Role as "Data Entry"

### ISSUE THREAD

**Issue by Glenalth** [amtgard/ORK3#85]
When editing from the Members section of a unit, if you select a "Member" role player, the role field automatically fills with "Data Entry". If you select someone with the "Captain" role it fills in properly. I did not test with "Lord" or "Organizer."

**Comment by jrtaylor-com** [comment]
Both Member and Data Entry roles have a value of "member" So the selected value could be more of a display issue if the two roles should be "member" otherwise the value for the Data Entry role needs to be defined so that we can update that value.

**Comment by jrtaylor-com** [comment]
@Glenalth per my last comment, should we be updating the underlying value of the Data Entry selection?

**Comment by Glenalth** [comment]
I thought I had responded to this previously...

I don't believe there is a need for the "Data Entry" role at all unless there is some underlying mechanic for giving permissions to edit or add attendance for events created by an event unit.

**Comment by jrtaylor-com** [comment]
Ok looks like we can remove that select option from the template. Thanks!

@esdraelon  branch https://github.com/amtgard/ORK3/tree/fix/unit/issue85-remove-data-entry-role will resolve this issue

**Comment by esdraelon** [comment]
Fixed and released in branch sprint-2017-10-16
