### ISSUE TITLE
Fatal Error, memory limit

### ISSUE THREAD

**Issue by Glenalth** [amtgard/ORK3#88]
Another reason to swap servers?

From: http://amtgard.com/ork/orkui/index.php?Route=Player/index/

"Fatal error: Allowed memory size of 94371840 bytes exhausted (tried to allocate 72 bytes) in /home/amtgard/amtgard.com/ork/system/lib/ork3/class.Player.php on line 175"

**Comment by Glenalth** [comment]
Which seems to be just a bad URL anyway, but I can't find the page on the ORK with the link that sent me there.

**Comment by amtgard** [comment]
Some reflection to validate method calls on the Routes prior to launching the specific Route method.
