### ISSUE TITLE
awards disappearing/being deleted

### ISSUE THREAD

**Issue by Tyedye** [amtgard/ORK3#90]
I recieved a message from Whystler,  Baron of White Stone Valley in the Northern Empire (Guelph Ontario AmtGard group) 

"I experienced a couple of weird Orknesses.  One, I might have a reasonable understanding about.

I was given my 4th Dragon last December by Finola (the regent of the northern empire) and entered it into the Ork that month.  It wasn't a week later that it disspeared.  I tried to enter it again and it didn't stick.  I'm guessing that it's possible a person perhaps cannot enter their own awards.  So I messaged Finola that she might need to do it herself.  That didn't worry me.

Today someone pointed out that Lily MacEwan od Chaol Glenn (Becka Dupuis) from our Barony who has had her Lady title since last year suddently no longer has her Lady title showing up."

I looked at the people in question, this is not a case of the blanked awards. NE was not effected by that, and the award is not still there.

His facebook name is T. Shawn Johnson, https://www.facebook.com/t.shawn.johnson he seems like a competent person if some form of further troubleshooting is needed.

Of possible relation, it sounds like the chancellor was changed, and then got rolled back in some way.
"Arik (Azkall) , who is our chancellor, all of sudden found that the password he thought he should use was not working.  So he asked me to go in and see if I could change his password to one he recommended.  I did so.  But I have not heard whether he is still experiencing problems ... but ...

Just now as I investigated Becka's account, I noticed that she is still listed as our chancellor, and she is actually our previous chancellor.  That was changed to Arik (Azkall)."

I cant rule out someone manually changing things like this, but he was at least surprised by the idea so it is unlikely to be some kind of feud. I told him to reenter them by hand, but that I would pass word along for someone to look into.

**Comment by amtgard** [comment]
I'm not sure there's anything actionable here.
