### ISSUE TITLE
Player page "Given By" link points directly to linked player admin page

### ISSUE THREAD

**Issue by Glenalth** [amtgard/ORK3#93]
On player pages, "Awards & Titles" section, "Given By" player name link points directly to admin view for that player instead of the normal view.

**Comment by jrtaylor-com** [comment]
Glenalth can you confirm that this only occurs when you are logged into an admin account?

I just tested as a normal guest user and it appears to link correctly.

**Comment by Glenalth** [comment]
It was linking to the admin view for the linked player, not account or login related.

It looks like it has been fixed from the player page. It still links to the admin view of the awarding player if you follow the link from a player admin view, but that is probably fine.

**Comment by jrtaylor-com** [comment]
Sounds good, closing out.
