### ISSUE TITLE
Atlas is blank when via HTTPS

### ISSUE THREAD

**Issue by Glenalth** [amtgard/ORK3#96]
It looks like the atlas map can't draw when you are connected via https. Probably wouldn't be a big deal except that Google searches for Amtgard Atlas send you to the secure version.

**Comment by BenOvermyer** [comment]
This may have more to do with the server configuration than the application itself.

**Comment by esdraelon** [comment]
The map server at google does not support HTTPS correctly.

There may be a different way to access maps now.

Noah

**Comment by Glenalth** [comment]
At some point, this was fixed.
